shellEmulator: true
packages:
  - packages/*

catalog:
  '@eslint/js': ^9.39.2
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^25.1.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  lucide-react: ^1.11.0
  tailwindcss: ^4.1.18
  tsdown: ^0.20.0
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  zod: ^3.25.76
onlyBuiltDependencies:
  - electron
  - esbuild
